### ISSUE TITLE
Webaite formats bad on mobile

### ISSUE THREAD

**Issue by Alistair-L-R** [Mole1424/website#5]
Smh bro

Also sned me stuff for dofe

**Comment by Mole1424** [comment]
Certainly! Here's a professional response you can use to address an irrelevant and improperly worded GitHub issue:

Dear [User's Name],

Thank you for reaching out and taking the time to submit an issue. We appreciate your interest in improving our project.

After reviewing your submission, it appears that the issue you reported does not pertain to the scope or functionality of this repository. Additionally, the description provided is somewhat unclear and lacks specific details that would help us understand and address the concern effectively.

To better assist you, please consider the following guidelines for submitting issues:

    Relevance: Ensure that the issue is directly related to the project and its intended use.
    Clarity: Provide a clear and concise description of the issue. Include steps to reproduce the problem, expected behavior, and any relevant screenshots or logs.
    Specificity: Be as specific as possible about the problem you are encountering. This helps us diagnose and resolve the issue more efficiently.

If you believe this issue is still relevant, we kindly ask you to update the issue with additional information following the guidelines above. If the issue is not related to this project, we recommend seeking support through the appropriate channels.

Thank you for your understanding and cooperation.

Best regards,

[Your Name]
[Your Role/Position]
[Project/Organization Name]
